name: 'Team Resourceful'
description: 'some action'
author: 'Team Resourceful'
inputs:
    release_version:
        required: true
        description: 'The version number that gets prepended to the changelog before the changes are listed out.'
        default: ''
    changelog_file:
        required: true
        description: 'The changelog file to be modified.'
        default: 'changelog.md'
    github_token:
        required: true
        description: 'A GitHub token to be able to read and parse the commit history.'
        default: ''
runs:
    using: 'node16'
    main: 'dist/index.js'